### ISSUE TITLE
[question] cloning my own install

### ISSUE THREAD

**Issue by shawngraham** [JonathanReeve/dh-usb#12]
Hi again,

I've been having lots of fun with this, adding bits and bobs to it. In terms of getting my modified version into the hands of my students - would it be best to build from scratch and have my additions rolled in at that point? I see various tools out there (clonezilla, etc) with which I suppose I could clone from my dh-usb onto fresh sticks, or presumably make an .iso available somewhere. Haven't done much in that regards, so apologies for the noobness.

Thanks,  
Shawn

**Comment by JonathanReeve** [comment]
Awesome. If there's anything you think should be in it that isn't, let me know. I think typically any utility that can make and write disk images (.img) will work for your customized version. I typically use GNOME Disks, but if you used MacOS Disk Utility to write the initial image, it should probably work to make a new .img from your disk. I tried CloneZilla once, but it seemed somewhat complicated, so I gave it up. Anyway, let me know what works for you, and I'll pass along that information in the README.
